projects:
  app:
    schemaPath: 'src/schema/schema.graphql'
    extensions:
      endpoints:
        default: 'http://localhost:6969/graphql'
  prisma:
    schemaPath: 'src/schema/generated/prisma.graphql'
    extensions:
      prisma: prisma.yml
